layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/
repository: izhaan123/izhaan123.github.io

linkedin_username:    izhaan-zubair-087938178
facebook_username:    IzH44n

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Virtual Reality
    web_url: https://github.com/topics/virtual-reality
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSE6XUfdyi9Mhw7Duzx2lQX73p55jyxosnpG7NpKXjMmvqPoUiT4A

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://cdn0.iconfinder.com/data/icons/trending-tech/94/artificial_intelligence-512.png

  - name: Game Engines
    web_url: https://github.com/topics/game-engine
    image_url: https://static1.squarespace.com/static/54c2431ee4b0bad937270c4d/t/5b7c2e3c70a6ad69e1807d19/1534864980753/mesh-icon.png?format=1500w

theme: jekyll-theme-cayman
