layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/
repository: izhaan123/izhaan123.github.io

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Virtual Reality
    web_url: https://github.com/topics/virtual-reality
    image_url: https://cmkt-image-prd.global.ssl.fastly.net/0.1.0/ps/2093767/580/386/m1/fpnw/wm0/oculus3_cm-.jpg?1483635812&s=3d3a1e7324168861a75a758baf4517cc

  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://cdn0.iconfinder.com/data/icons/trending-tech/94/artificial_intelligence-512.png

  - name: Game Engines
    web_url: https://github.com/topics/game-engine
    image_url: https://static1.squarespace.com/static/54c2431ee4b0bad937270c4d/t/5b7c2e3c70a6ad69e1807d19/1534864980753/mesh-icon.png?format=1500w

theme: jekyll-theme-cayman
