layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/
repository: izhaan123/izhaan123.github.io

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Virtual Reality
    web_url: https://github.com/topics/virtual-reality
    image_url: https://cmkt-image-prd.global.ssl.fastly.net/0.1.0/ps/2093767/580/386/m1/fpnw/wm0/oculus3_cm-.jpg?1483635812&s=3d3a1e7324168861a75a758baf4517cc

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

theme: jekyll-theme-cayman
